name: Update EMA Scanner

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Libraries
        run: pip install -r scanner/requirements.txt

      - name: Run Scanner
        run: python scanner/scanner.py

      - name: Commit Results
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -m "Updated EMA data" || echo "No changes"
          git push
